export const CHARACTER_UPDATE_LIST = 'CHARACTER_UPDATE_LIST'
export const CHARACTER_UPDATE_CHARACTER = 'CHARACTER_UPDATE_CHARACTER'
export const CHARACTER_SET_FETCHING = 'CHARACTER_SET_FETCHING'
export const CHARACTER_POST_NEWCHAR = 'CHARACTER_POST_NEWCHAR'